package tr.edu.fsm.FSMVUDersProgRS.Yonetim;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Yonetici generated by hbm2java
 */
@Entity
@Table(name = "Yonetici", catalog = "sql286097", uniqueConstraints = @UniqueConstraint(columnNames = "yonetici_kodu") )
public class Yonetici implements java.io.Serializable {

	private Integer id;
	private String yoneticiKodu;
	private String adi;
	private String soyadi;
	private String email;
	private String parola;

	public Yonetici() {
	}

	public Yonetici(String yoneticiKodu, String adi, String soyadi, String email, String parola) {
		this.yoneticiKodu = yoneticiKodu;
		this.adi = adi;
		this.soyadi = soyadi;
		this.email = email;
		this.parola = parola;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "yonetici_kodu", unique = true, nullable = false, length = 45)
	public String getYoneticiKodu() {
		return this.yoneticiKodu;
	}

	public void setYoneticiKodu(String yoneticiKodu) {
		this.yoneticiKodu = yoneticiKodu;
	}

	@Column(name = "adi", nullable = false, length = 45)
	public String getAdi() {
		return this.adi;
	}

	public void setAdi(String adi) {
		this.adi = adi;
	}

	@Column(name = "soyadi", nullable = false, length = 45)
	public String getSoyadi() {
		return this.soyadi;
	}

	public void setSoyadi(String soyadi) {
		this.soyadi = soyadi;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "parola", nullable = false, length = 45)
	public String getParola() {
		return this.parola;
	}

	public void setParola(String parola) {
		this.parola = parola;
	}

}
