-- MySQL Script generated by MySQL Workbench
-- 08/07/15 11:06:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Derslik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Derslik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Derslik` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `derslik_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `derslik_adi` VARCHAR(45) NOT NULL COMMENT '',
  `bolum_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ders` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ders_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `ders_adi` VARCHAR(90) NOT NULL COMMENT '',
  `kredi` INT NULL COMMENT '',
  `akts` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ders_tarihi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ders_tarihi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ders_tarihi` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ders_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `derslik_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `baslangic_tarihi` DATETIME NOT NULL COMMENT '',
  `bitis_tarihi` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bolum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bolum` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bolum` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `bolum_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `bolum_adi` VARCHAR(70) NOT NULL COMMENT '',
  `fakulte_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `bolum_kodu_UNIQUE` (`bolum_kodu` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fakulte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fakulte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fakulte` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fakulte_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `fakulte_adi` VARCHAR(45) NOT NULL COMMENT '',
  `yerleske_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Yerleske`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Yerleske` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Yerleske` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `yerleske_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `yerleske_adi` VARCHAR(45) NOT NULL COMMENT '',
  `adres` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Yonetici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Yonetici` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Yonetici` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `yonetici_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `adi` VARCHAR(45) NOT NULL COMMENT '',
  `soyadi` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `parola` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `yonetici_kodu_UNIQUE` (`yonetici_kodu` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Akademisyen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Akademisyen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Akademisyen` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `akademisyen_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `adi` VARCHAR(45) NOT NULL COMMENT '',
  `soyadi` VARCHAR(45) NOT NULL COMMENT '',
  `unvani` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `parola` VARCHAR(45) NOT NULL COMMENT '',
  UNIQUE INDEX `akademisyen_kodu_UNIQUE` (`akademisyen_kodu` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ogrenci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ogrenci` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ogrenci` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ogrenci_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `adi` VARCHAR(45) NOT NULL COMMENT '',
  `soyadi` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `parola` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `ogrenci_no_UNIQUE` (`ogrenci_kodu` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Donem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Donem` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `donem_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `donem_adi` VARCHAR(90) NOT NULL COMMENT '',
  `baslangic_tarihi` DATETIME NOT NULL COMMENT '',
  `bitis_tarihi` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`akademisyen_ders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`akademisyen_ders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`akademisyen_ders` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `akademisyen_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `ders_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bolum_ogrenci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bolum_ogrenci` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bolum_ogrenci` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `bolum_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `ogrenci_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ders_ogrenci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ders_ogrenci` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ders_ogrenci` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ders_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `ogrenci_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ders_donem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ders_donem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ders_donem` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ders_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `donem_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donem_ogrenci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Donem_ogrenci` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Donem_ogrenci` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `donem_kodu` VARCHAR(45) NOT NULL COMMENT '',
  `ogrenci_kodu` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
