package tr.edu.fsm.FSMVUDersProgRS.Derslik;
// default package

// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Derslik generated by hbm2java
 */
@Entity
@Table(name = "Derslik", catalog = "sql286097")
public class Derslik implements java.io.Serializable {

	private static Derslik instance;
	private Integer id;
	private String derslikKodu;
	private String derslikAdi;
	private String bolumKodu;

	private Derslik() {
	}

	public static Derslik getInstance() {
		if (instance == null)
			instance = new Derslik();
		return instance;
	}

	public void setAll(String derslikKodu, String derslikAdi, String bolumKodu) {
		this.derslikKodu = derslikKodu;
		this.derslikAdi = derslikAdi;
		this.bolumKodu = bolumKodu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "derslik_kodu", nullable = false, length = 45)
	public String getDerslikKodu() {
		return this.derslikKodu;
	}

	public void setDerslikKodu(String derslikKodu) {
		this.derslikKodu = derslikKodu;
	}

	@Column(name = "derslik_adi", nullable = false, length = 45)
	public String getDerslikAdi() {
		return this.derslikAdi;
	}

	public void setDerslikAdi(String derslikAdi) {
		this.derslikAdi = derslikAdi;
	}

	@Column(name = "bolum_kodu", nullable = false, length = 45)
	public String getBolumKodu() {
		return this.bolumKodu;
	}

	public void setBolumKodu(String bolumKodu) {
		this.bolumKodu = bolumKodu;
	}

}
