package tr.edu.fsm.FSMVUDersProgRS.Derslik;
// Generated 03.AIu.2015 14:34:14 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Derslik generated by hbm2java
 */
@Entity
@Table(name = "Derslik", catalog = "sql285436", uniqueConstraints = { @UniqueConstraint(columnNames = "derslik_kodu"),
		@UniqueConstraint(columnNames = "derslik_adi"), @UniqueConstraint(columnNames = "sorumlu_bolum_id") })
public class Derslik implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2624592274558094905L;
	private Integer id;
	private int derslikKodu;
	private String derslikAdi;
	private int sorumluBolumId;

	public Derslik() {
	}

	public Derslik(int derslikKodu, String derslikAdi, int sorumluBolumId) {
       this.derslikKodu = derslikKodu;
       this.derslikAdi = derslikAdi;
       this.sorumluBolumId = sorumluBolumId;
    }

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "derslik_kodu", unique = true, nullable = false)
	public int getDerslikKodu() {
		return this.derslikKodu;
	}

	public void setDerslikKodu(int derslikKodu) {
		this.derslikKodu = derslikKodu;
	}

	@Column(name = "derslik_adi", unique = true, nullable = false, length = 20)
	public String getDerslikAdi() {
		return this.derslikAdi;
	}

	public void setDerslikAdi(String derslikAdi) {
		this.derslikAdi = derslikAdi;
	}

	@Column(name="sorumlu_bolum_id", unique=true, nullable=false)
    public int getSorumluBolumId() {
        return this.sorumluBolumId;
    }

	public void setSorumluBolumId(int sorumluBolumId) {
        this.sorumluBolumId = sorumluBolumId;
    }




}
