package tr.edu.fsm.FSMVUDersProgRS.Donem;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DersDonem generated by hbm2java
 */
@Entity
@Table(name = "Ders_donem", catalog = "sql286097")
public class DersDonem implements java.io.Serializable {

	private Integer id;
	private String dersKodu;
	private String donemKodu;

	public DersDonem() {
	}

	public DersDonem(String dersKodu, String donemKodu) {
		this.dersKodu = dersKodu;
		this.donemKodu = donemKodu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ders_kodu", nullable = false, length = 45)
	public String getDersKodu() {
		return this.dersKodu;
	}

	public void setDersKodu(String dersKodu) {
		this.dersKodu = dersKodu;
	}

	@Column(name = "donem_kodu", nullable = false, length = 45)
	public String getDonemKodu() {
		return this.donemKodu;
	}

	public void setDonemKodu(String donemKodu) {
		this.donemKodu = donemKodu;
	}

}
