package tr.edu.fsm.FSMVUDersProgRS.Donem;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donem generated by hbm2java
 */
@Entity
@Table(name = "Donem", catalog = "sql286097")
public class Donem implements java.io.Serializable {

	private Integer id;
	private String donemKodu;
	private String donemAdi;
	private Date baslangicTarihi;
	private Date bitisTarihi;

	public Donem() {
	}

	public Donem(String donemKodu, String donemAdi, Date baslangicTarihi, Date bitisTarihi) {
		this.donemKodu = donemKodu;
		this.donemAdi = donemAdi;
		this.baslangicTarihi = baslangicTarihi;
		this.bitisTarihi = bitisTarihi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "donem_kodu", nullable = false, length = 45)
	public String getDonemKodu() {
		return this.donemKodu;
	}

	public void setDonemKodu(String donemKodu) {
		this.donemKodu = donemKodu;
	}

	@Column(name = "donem_adi", nullable = false, length = 90)
	public String getDonemAdi() {
		return this.donemAdi;
	}

	public void setDonemAdi(String donemAdi) {
		this.donemAdi = donemAdi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "baslangic_tarihi", nullable = false, length = 19)
	public Date getBaslangicTarihi() {
		return this.baslangicTarihi;
	}

	public void setBaslangicTarihi(Date baslangicTarihi) {
		this.baslangicTarihi = baslangicTarihi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bitis_tarihi", nullable = false, length = 19)
	public Date getBitisTarihi() {
		return this.bitisTarihi;
	}

	public void setBitisTarihi(Date bitisTarihi) {
		this.bitisTarihi = bitisTarihi;
	}

}
