package tr.edu.fsm.FSMVUDersProgRS.Akademisyen;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Akademisyen generated by hbm2java
 */
@Entity
@Table(name = "Akademisyen", catalog = "sql286097", uniqueConstraints = @UniqueConstraint(columnNames = "akademisyen_kodu") )
public class Akademisyen implements java.io.Serializable {

	private Integer id;
	private String akademisyenKodu;
	private String adi;
	private String soyadi;
	private String unvani;
	private String email;
	private String parola;

	public Akademisyen() {
	}

	public Akademisyen(String akademisyenKodu, String adi, String soyadi, String email, String parola) {
		this.akademisyenKodu = akademisyenKodu;
		this.adi = adi;
		this.soyadi = soyadi;
		this.email = email;
		this.parola = parola;
	}

	public Akademisyen(String akademisyenKodu, String adi, String soyadi, String unvani, String email, String parola) {
		this.akademisyenKodu = akademisyenKodu;
		this.adi = adi;
		this.soyadi = soyadi;
		this.unvani = unvani;
		this.email = email;
		this.parola = parola;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "akademisyen_kodu", unique = true, nullable = false, length = 45)
	public String getAkademisyenKodu() {
		return this.akademisyenKodu;
	}

	public void setAkademisyenKodu(String akademisyenKodu) {
		this.akademisyenKodu = akademisyenKodu;
	}

	@Column(name = "adi", nullable = false, length = 45)
	public String getAdi() {
		return this.adi;
	}

	public void setAdi(String adi) {
		this.adi = adi;
	}

	@Column(name = "soyadi", nullable = false, length = 45)
	public String getSoyadi() {
		return this.soyadi;
	}

	public void setSoyadi(String soyadi) {
		this.soyadi = soyadi;
	}

	@Column(name = "unvani", length = 45)
	public String getUnvani() {
		return this.unvani;
	}

	public void setUnvani(String unvani) {
		this.unvani = unvani;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "parola", nullable = false, length = 45)
	public String getParola() {
		return this.parola;
	}

	public void setParola(String parola) {
		this.parola = parola;
	}

}
