package tr.edu.fsm.FSMVUDersProgRS.Akademisyen;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AkademisyenDers generated by hbm2java
 */
@Entity
@Table(name = "Akademisyen_ders", catalog = "sql286097")
public class AkademisyenDers implements java.io.Serializable {

	private Integer id;
	private String akademisyenKodu;
	private String dersKodu;

	public AkademisyenDers() {
	}

	public AkademisyenDers(String akademisyenKodu, String dersKodu) {
		this.akademisyenKodu = akademisyenKodu;
		this.dersKodu = dersKodu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "akademisyen_kodu", nullable = false, length = 45)
	public String getAkademisyenKodu() {
		return this.akademisyenKodu;
	}

	public void setAkademisyenKodu(String akademisyenKodu) {
		this.akademisyenKodu = akademisyenKodu;
	}

	@Column(name = "ders_kodu", nullable = false, length = 45)
	public String getDersKodu() {
		return this.dersKodu;
	}

	public void setDersKodu(String dersKodu) {
		this.dersKodu = dersKodu;
	}

}
