package tr.edu.fsm.FSMVUDersProgRS.Ders;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ders generated by hbm2java
 */
@Entity
@Table(name = "Ders", catalog = "sql286097")
public class Ders implements java.io.Serializable {

	private Integer id;
	private String dersKodu;
	private String dersAdi;
	private Integer kredi;
	private Integer akts;

	public Ders() {
	}

	public Ders(String dersKodu, String dersAdi) {
		this.dersKodu = dersKodu;
		this.dersAdi = dersAdi;
	}

	public Ders(String dersKodu, String dersAdi, Integer kredi, Integer akts) {
		this.dersKodu = dersKodu;
		this.dersAdi = dersAdi;
		this.kredi = kredi;
		this.akts = akts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ders_kodu", nullable = false, length = 45)
	public String getDersKodu() {
		return this.dersKodu;
	}

	public void setDersKodu(String dersKodu) {
		this.dersKodu = dersKodu;
	}

	@Column(name = "ders_adi", nullable = false, length = 90)
	public String getDersAdi() {
		return this.dersAdi;
	}

	public void setDersAdi(String dersAdi) {
		this.dersAdi = dersAdi;
	}

	@Column(name = "kredi")
	public Integer getKredi() {
		return this.kredi;
	}

	public void setKredi(Integer kredi) {
		this.kredi = kredi;
	}

	@Column(name = "akts")
	public Integer getAkts() {
		return this.akts;
	}

	public void setAkts(Integer akts) {
		this.akts = akts;
	}

}
