package tr.edu.fsm.FSMVUDersProgRS.Ders;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DersTarihi generated by hbm2java
 */
@Entity
@Table(name = "Ders_tarihi", catalog = "sql286097")
public class DersTarihi implements java.io.Serializable {

	private Integer id;
	private String dersKodu;
	private String derslikKodu;
	private Date baslangicTarihi;
	private Date bitisTarihi;

	public DersTarihi() {
	}

	public DersTarihi(String dersKodu, String derslikKodu, Date baslangicTarihi, Date bitisTarihi) {
		this.dersKodu = dersKodu;
		this.derslikKodu = derslikKodu;
		this.baslangicTarihi = baslangicTarihi;
		this.bitisTarihi = bitisTarihi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ders_kodu", nullable = false, length = 45)
	public String getDersKodu() {
		return this.dersKodu;
	}

	public void setDersKodu(String dersKodu) {
		this.dersKodu = dersKodu;
	}

	@Column(name = "derslik_kodu", nullable = false, length = 45)
	public String getDerslikKodu() {
		return this.derslikKodu;
	}

	public void setDerslikKodu(String derslikKodu) {
		this.derslikKodu = derslikKodu;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "baslangic_tarihi", nullable = false, length = 19)
	public Date getBaslangicTarihi() {
		return this.baslangicTarihi;
	}

	public void setBaslangicTarihi(Date baslangicTarihi) {
		this.baslangicTarihi = baslangicTarihi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bitis_tarihi", nullable = false, length = 19)
	public Date getBitisTarihi() {
		return this.bitisTarihi;
	}

	public void setBitisTarihi(Date bitisTarihi) {
		this.bitisTarihi = bitisTarihi;
	}

}
