package tr.edu.fsm.FSMVUDersProgRS.Bolum;
// default package
// Generated 07.A�u.2015 11:35:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bolum generated by hbm2java
 */
@Entity
@Table(name = "Bolum", catalog = "sql286097", uniqueConstraints = @UniqueConstraint(columnNames = "bolum_kodu") )
public class Bolum implements java.io.Serializable {

	private Integer id;
	private String bolumKodu;
	private String bolumAdi;
	private String fakulteKodu;

	public Bolum() {
	}

	public Bolum(String bolumKodu, String bolumAdi, String fakulteKodu) {
		this.bolumKodu = bolumKodu;
		this.bolumAdi = bolumAdi;
		this.fakulteKodu = fakulteKodu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bolum_kodu", unique = true, nullable = false, length = 45)
	public String getBolumKodu() {
		return this.bolumKodu;
	}

	public void setBolumKodu(String bolumKodu) {
		this.bolumKodu = bolumKodu;
	}

	@Column(name = "bolum_adi", nullable = false, length = 70)
	public String getBolumAdi() {
		return this.bolumAdi;
	}

	public void setBolumAdi(String bolumAdi) {
		this.bolumAdi = bolumAdi;
	}

	@Column(name = "fakulte_kodu", nullable = false, length = 45)
	public String getFakulteKodu() {
		return this.fakulteKodu;
	}

	public void setFakulteKodu(String fakulteKodu) {
		this.fakulteKodu = fakulteKodu;
	}

}
